# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_gen import qa_pb2 as grpc__gen_dot_qa__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_gen/qa_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class QAServiceStub(object):
    """The qa service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCollection = channel.unary_unary(
                '/qa.QAService/CreateCollection',
                request_serializer=grpc__gen_dot_qa__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=grpc__gen_dot_qa__pb2.CreateCollectionResponse.FromString,
                _registered_method=True)
        self.GetAnswer = channel.unary_unary(
                '/qa.QAService/GetAnswer',
                request_serializer=grpc__gen_dot_qa__pb2.GetAnswerRequest.SerializeToString,
                response_deserializer=grpc__gen_dot_qa__pb2.Answer.FromString,
                _registered_method=True)


class QAServiceServicer(object):
    """The qa service definition
    """

    def CreateCollection(self, request, context):
        """Creates a new collection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnswer(self, request, context):
        """Gets an answer for a given question from the specified collection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QAServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=grpc__gen_dot_qa__pb2.CreateCollectionRequest.FromString,
                    response_serializer=grpc__gen_dot_qa__pb2.CreateCollectionResponse.SerializeToString,
            ),
            'GetAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnswer,
                    request_deserializer=grpc__gen_dot_qa__pb2.GetAnswerRequest.FromString,
                    response_serializer=grpc__gen_dot_qa__pb2.Answer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qa.QAService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qa.QAService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QAService(object):
    """The qa service definition
    """

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.QAService/CreateCollection',
            grpc__gen_dot_qa__pb2.CreateCollectionRequest.SerializeToString,
            grpc__gen_dot_qa__pb2.CreateCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.QAService/GetAnswer',
            grpc__gen_dot_qa__pb2.GetAnswerRequest.SerializeToString,
            grpc__gen_dot_qa__pb2.Answer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
