# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_gen/qa.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11grpc_gen/qa.proto\x12\x02qa\"9\n\x17\x43reateCollectionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x66ile_url\x18\x02 \x01(\t\"\x1a\n\x18\x43reateCollectionResponse\"=\n\x10GetAnswerRequest\x12\x17\n\x0f\x63ollection_name\x18\x01 \x01(\t\x12\x10\n\x08question\x18\x02 \x01(\t\"\x16\n\x06\x41nswer\x12\x0c\n\x04text\x18\x01 \x01(\t2\x89\x01\n\tQAService\x12M\n\x10\x43reateCollection\x12\x1b.qa.CreateCollectionRequest\x1a\x1c.qa.CreateCollectionResponse\x12-\n\tGetAnswer\x12\x14.qa.GetAnswerRequest\x1a\n.qa.AnswerB7Z5github.com/didil/simple-text-rag-go-frontend/grpc_genb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_gen.qa_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/didil/simple-text-rag-go-frontend/grpc_gen'
  _globals['_CREATECOLLECTIONREQUEST']._serialized_start=25
  _globals['_CREATECOLLECTIONREQUEST']._serialized_end=82
  _globals['_CREATECOLLECTIONRESPONSE']._serialized_start=84
  _globals['_CREATECOLLECTIONRESPONSE']._serialized_end=110
  _globals['_GETANSWERREQUEST']._serialized_start=112
  _globals['_GETANSWERREQUEST']._serialized_end=173
  _globals['_ANSWER']._serialized_start=175
  _globals['_ANSWER']._serialized_end=197
  _globals['_QASERVICE']._serialized_start=200
  _globals['_QASERVICE']._serialized_end=337
# @@protoc_insertion_point(module_scope)
